server:
  telegram_worker: true

openrouter:
  model: "mistralai/mistral-7b-instruct:free"
  referer: "https://github.com/nurashi/Newton"

database:
  host: "${DB_HOST}"
  port: 5432
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME}"