server:
  telegram_worker: true

openrouter:
  model: "mistralai/mistral-7b-instruct:free"
  referer: "https://github.com/nurashi/Newton"

database:
  host: "postgres"
  port: 5432
  user: "aiuser"
  password: "aipassword"
  name: "aibot"